.TH "Ball" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ball
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBhiex::ImageBlock\fP \fBimg\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBvx\fP"
.br
.ti -1c
.RI "float \fBvy\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 main\&.cpp 第 17 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBhiex::ImageBlock\fP Ball::img"

.PP
在文件 main\&.cpp 第 19 行定义\&.
.SS "float Ball::vx"

.PP
在文件 main\&.cpp 第 21 行定义\&.
.SS "float Ball::vy"

.PP
在文件 main\&.cpp 第 21 行定义\&.
.SS "float Ball::x"

.PP
在文件 main\&.cpp 第 20 行定义\&.
.SS "float Ball::y"

.PP
在文件 main\&.cpp 第 20 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
