.TH "bug" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug 列表 

.IP "\fB类 \fBHiEasyX::Gif\fP \fP" 1c
 
.IP "\fB成员 \fBHiEasyX::initgraph_win32\fP (int w, int h, int flag, LPCTSTR lpszWndTitle, WNDPROC WindowProcess, HWND hParent)\fP" 1c
 不建议大批量创建绘图窗口，如果必要，请适当添加延时，否则可能导致未知问题。 
.IP "\fB类 \fBHiEasyX::SysGroupBox\fP \fP" 1c
 分组框背景绘制有 Bug，请斟酌使用 
.PP

