.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/Button.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/Button.h \- HiGUI 控件分支：按钮控件  

.SH SYNOPSIS
.br
.PP
\fC#include 'ControlBase\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::Button\fP"
.br
.RI "按钮控件 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SH "详细描述"
.PP 
HiGUI 控件分支：按钮控件 


.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBButton\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
