.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI 目录参考" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBButton\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBButton\&.h\fP"
.br
.RI "HiGUI 控件分支：按钮控件 "
.ti -1c
.RI "文件 \fBControlBase\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBControlBase\&.h\fP"
.br
.RI "HiGUI 控件分支：控件基础 "
.ti -1c
.RI "文件 \fBHiGUI\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的图形用户界面模块 "
.ti -1c
.RI "文件 \fBPage\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBPage\&.h\fP"
.br
.RI "HiGUI 控件分支：页控件 "
.ti -1c
.RI "文件 \fBProgressCtrl\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBProgressCtrl\&.h\fP"
.br
.RI "HiGUI 控件分支：进度条控件 "
.ti -1c
.RI "文件 \fBScrollBar\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBScrollBar\&.h\fP"
.br
.RI "HiGUI 控件分支：滚动条控件 "
.ti -1c
.RI "文件 \fBStatic\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBStatic\&.h\fP"
.br
.RI "HiGUI 控件分支：静态控件 "
.in -1c
