.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX 目录参考" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX 目录参考
.SH SYNOPSIS
.br
.PP
.SS "目录"

.in +1c
.ti -1c
.RI "目录 \fBHiGUI\fP"
.br
.ti -1c
.RI "目录 \fBHiSysGUI\fP"
.br
.in -1c
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBHiCanvas\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiCanvas\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的画布模块 "
.ti -1c
.RI "文件 \fBHiContainer\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiContainer\&.h\fP"
.br
.ti -1c
.RI "文件 \fBHiDef\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的配置定义 "
.ti -1c
.RI "文件 \fBHiDrawingProperty\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiDrawingProperty\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的绘图属性存储模块 "
.ti -1c
.RI "文件 \fBHiFPS\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiFPS\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的帧率模块 "
.ti -1c
.RI "文件 \fBHiFunc\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiFunc\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的常用杂项函数 "
.ti -1c
.RI "文件 \fBHiGdiplus\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiGdiplus\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的 GDI+ 绘图模块 "
.ti -1c
.RI "文件 \fBHiGif\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiGif\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的动图模块 "
.ti -1c
.RI "文件 \fBHiIcon\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiIcon\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的图标模块 "
.ti -1c
.RI "文件 \fBHiMacro\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的常用宏定义模块 "
.ti -1c
.RI "文件 \fBHiMouseDrag\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiMouseDrag\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的鼠标拖动处理模块 "
.ti -1c
.RI "文件 \fBHiMusicMCI\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiMusicMCI\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的声音模块 "
.ti -1c
.RI "文件 \fBHiStart\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiStart\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的开始界面渲染模块 "
.ti -1c
.RI "文件 \fBHiWindow\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBHiWindow\&.h\fP"
.br
.RI "\fBHiEasyX\fP 库的窗口模块 "
.in -1c
