.TH "HiEasyX::DrawingProperty" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::DrawingProperty
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiDrawingProperty\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "void \fBSaveProperty\fP ()"
.br
.RI "保存当前所有的绘图属性 "
.ti -1c
.RI "void \fBSaveWorkingImageOnly\fP ()"
.br
.RI "只保存当前绘图对象 "
.ti -1c
.RI "void \fBApplyProperty\fP ()"
.br
.RI "应用保存的所有绘图属性 "
.ti -1c
.RI "void \fBApplyWorkingImageOnly\fP ()"
.br
.RI "只恢复绘图对象 "
.ti -1c
.RI "bool \fBIsSaved\fP ()"
.br
.RI "判断是否保存了绘图属性 "
.ti -1c
.RI "void \fBReset\fP ()"
.br
.RI "重置保存状态 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "IMAGE * \fBm_pImg\fP"
.br
.ti -1c
.RI "float \fBm_xasp\fP"
.br
.ti -1c
.RI "float \fBm_yasp\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cBk\fP"
.br
.ti -1c
.RI "int \fBm_nBkMode\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cFill\fP"
.br
.ti -1c
.RI "FILLSTYLE \fBm_fillstyle\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cLine\fP"
.br
.ti -1c
.RI "LINESTYLE \fBm_linestyle\fP"
.br
.ti -1c
.RI "int \fBm_nPolyFillMode\fP"
.br
.ti -1c
.RI "int \fBm_nRop2Mode\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cText\fP"
.br
.ti -1c
.RI "LOGFONT \fBm_font\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
.nf

    绘图属性总控单元
.fi
.PP
.PP
.PP
.nf
 备注：
    EasyX 目前无法获取 setorigin 和 setcliprgn 所设置的值
.fi
.PP
 
.PP
在文件 HiDrawingProperty\&.h 第 21 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void HiEasyX::DrawingProperty::ApplyProperty ()"

.PP
应用保存的所有绘图属性 
.PP
在文件 HiDrawingProperty\&.cpp 第 29 行定义\&.
.PP
.nf
30     {
31         if (m_isSaved)
32         {
33             SetWorkingImage(m_pImg);
34             setaspectratio(m_xasp, m_yasp);
35             setbkcolor(m_cBk);
36             setbkmode(m_nBkMode);
37             setfillcolor(m_cFill);
38             setfillstyle(&m_fillstyle);
39             setlinecolor(m_cLine);
40             setlinestyle(&m_linestyle);
41             setpolyfillmode(m_nPolyFillMode);
42             setrop2(m_nRop2Mode);
43             settextcolor(m_cText);
44             settextstyle(&m_font);
45         }
46     }
.fi
.SS "void HiEasyX::DrawingProperty::ApplyWorkingImageOnly ()"

.PP
只恢复绘图对象 
.PP
在文件 HiDrawingProperty\&.cpp 第 48 行定义\&.
.PP
.nf
49     {
50         if (m_isSaved)
51         {
52             SetWorkingImage(m_pImg);
53         }
54     }
.fi
.SS "bool HiEasyX::DrawingProperty::IsSaved ()"

.PP
判断是否保存了绘图属性 
.PP
在文件 HiDrawingProperty\&.cpp 第 56 行定义\&.
.PP
.nf
57     {
58         return m_isSaved;
59     }
.fi
.SS "void HiEasyX::DrawingProperty::Reset ()"

.PP
重置保存状态 
.PP
在文件 HiDrawingProperty\&.cpp 第 61 行定义\&.
.PP
.nf
62     {
63         m_isSaved = false;
64     }
.fi
.SS "void HiEasyX::DrawingProperty::SaveProperty ()"

.PP
保存当前所有的绘图属性 
.PP
在文件 HiDrawingProperty\&.cpp 第 5 行定义\&.
.PP
.nf
6     {
7         m_pImg = GetWorkingImage();
8         getaspectratio(&m_xasp, &m_yasp);
9         m_cBk = getbkcolor();
10         m_nBkMode = getbkmode();
11         m_cFill = getfillcolor();
12         getfillstyle(&m_fillstyle);
13         m_cLine = getlinecolor();
14         getlinestyle(&m_linestyle);
15         m_nPolyFillMode = getpolyfillmode();
16         m_nRop2Mode = getrop2();
17         m_cText = gettextcolor();
18         gettextstyle(&m_font);
19 
20         m_isSaved = true;
21     }
.fi
.SS "void HiEasyX::DrawingProperty::SaveWorkingImageOnly ()"

.PP
只保存当前绘图对象 
.PP
在文件 HiDrawingProperty\&.cpp 第 23 行定义\&.
.PP
.nf
24     {
25         m_pImg = GetWorkingImage();
26         m_isSaved = true;
27     }
.fi
.SH "类成员变量说明"
.PP 
.SS "COLORREF HiEasyX::DrawingProperty::m_cBk"

.PP
在文件 HiDrawingProperty\&.h 第 29 行定义\&.
.SS "COLORREF HiEasyX::DrawingProperty::m_cFill"

.PP
在文件 HiDrawingProperty\&.h 第 31 行定义\&.
.SS "COLORREF HiEasyX::DrawingProperty::m_cLine"

.PP
在文件 HiDrawingProperty\&.h 第 33 行定义\&.
.SS "COLORREF HiEasyX::DrawingProperty::m_cText"

.PP
在文件 HiDrawingProperty\&.h 第 37 行定义\&.
.SS "FILLSTYLE HiEasyX::DrawingProperty::m_fillstyle"

.PP
在文件 HiDrawingProperty\&.h 第 32 行定义\&.
.SS "LOGFONT HiEasyX::DrawingProperty::m_font"

.PP
在文件 HiDrawingProperty\&.h 第 38 行定义\&.
.SS "LINESTYLE HiEasyX::DrawingProperty::m_linestyle"

.PP
在文件 HiDrawingProperty\&.h 第 34 行定义\&.
.SS "int HiEasyX::DrawingProperty::m_nBkMode"

.PP
在文件 HiDrawingProperty\&.h 第 30 行定义\&.
.SS "int HiEasyX::DrawingProperty::m_nPolyFillMode"

.PP
在文件 HiDrawingProperty\&.h 第 35 行定义\&.
.SS "int HiEasyX::DrawingProperty::m_nRop2Mode"

.PP
在文件 HiDrawingProperty\&.h 第 36 行定义\&.
.SS "IMAGE* HiEasyX::DrawingProperty::m_pImg"

.PP
在文件 HiDrawingProperty\&.h 第 27 行定义\&.
.SS "float HiEasyX::DrawingProperty::m_xasp"

.PP
在文件 HiDrawingProperty\&.h 第 28 行定义\&.
.SS "float HiEasyX::DrawingProperty::m_yasp"

.PP
在文件 HiDrawingProperty\&.h 第 28 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
