.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX.h \- \fBHiEasyX\fP 库头文件  

.SH SYNOPSIS
.br
.PP
\fC#include 'HiEasyX/HiDef\&.h'\fP
.br
\fC#include 'HiEasyX/HiMacro\&.h'\fP
.br
\fC#include 'HiEasyX/HiFunc\&.h'\fP
.br
\fC#include 'HiEasyX/HiFPS\&.h'\fP
.br
\fC#include 'HiEasyX/HiDrawingProperty\&.h'\fP
.br
\fC#include 'HiEasyX/HiMouseDrag\&.h'\fP
.br
\fC#include 'HiEasyX/HiMusicMCI\&.h'\fP
.br
\fC#include 'HiEasyX/HiGif\&.h'\fP
.br
\fC#include 'HiEasyX/HiWindow\&.h'\fP
.br
\fC#include 'HiEasyX/HiSysGUI/HiSysGUI\&.h'\fP
.br
\fC#include 'HiEasyX/HiGdiplus\&.h'\fP
.br
\fC#include 'HiEasyX/HiCanvas\&.h'\fP
.br
\fC#include 'HiEasyX/HiGUI/HiGUI\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HIEASYX_H__\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBHiEasyX\fP 库头文件 


.PP
\fB注解\fP
.RS 4
该库基于 EasyX 实现了在窗口、绘图、UI 等诸多方面的全面升级
.RE
.PP
\fB版本\fP
.RS 4
Ver 0\&.2\&.2 @envir VisualStudio 2022 | EasyX_20220901 | Windows 10 @site https://github.com/zouhuidong/HiEasyX
.RE
.PP
\fB作者\fP
.RS 4
huidong @email mailhuid@163.com @create 2022\&.07\&.20 
.RE
.PP
\fB日期\fP
.RS 4
2022\&.12\&.04 
.RE
.PP

.PP
在文件 \fBHiEasyX\&.h\fP 中定义\&.
.SH "宏定义说明"
.PP 
.SS "#define __HIEASYX_H__"

.PP
在文件 HiEasyX\&.h 第 18 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
