.TH "HiEasyX::Static::Char" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::Static::Char
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Static\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "TCHAR \fBch\fP"
.br
.ti -1c
.RI "COLORREF \fBcText\fP"
.br
.ti -1c
.RI "COLORREF \fBcBk\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 Static\&.h 第 20 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "COLORREF HiEasyX::Static::Char::cBk"

.PP
在文件 Static\&.h 第 24 行定义\&.
.SS "TCHAR HiEasyX::Static::Char::ch"

.PP
在文件 Static\&.h 第 22 行定义\&.
.SS "COLORREF HiEasyX::Static::Char::cText"

.PP
在文件 Static\&.h 第 23 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
