.TH "HiEasyX::SysEdit::PreStyle" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysEdit::PreStyle \- 编辑框预设样式（必须在创建前设置才有效）  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysEdit\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "bool \fBmultiline\fP = false"
.br
.RI "多行文本 "
.ti -1c
.RI "bool \fBcenter_text\fP = false"
.br
.RI "文本居中 "
.ti -1c
.RI "bool \fBvscroll\fP = false"
.br
.RI "拥有垂直滚动条 "
.ti -1c
.RI "bool \fBauto_vscroll\fP = false"
.br
.RI "自动垂直滚动 "
.ti -1c
.RI "bool \fBhscroll\fP = false"
.br
.RI "拥有水平滚动条 "
.ti -1c
.RI "bool \fBauto_hscroll\fP = false"
.br
.RI "自动水平滚动 "
.in -1c
.SH "详细描述"
.PP 
编辑框预设样式（必须在创建前设置才有效） 
.PP
在文件 SysEdit\&.h 第 59 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "bool HiEasyX::SysEdit::PreStyle::auto_hscroll = false"

.PP
自动水平滚动 
.PP
在文件 SysEdit\&.h 第 66 行定义\&.
.SS "bool HiEasyX::SysEdit::PreStyle::auto_vscroll = false"

.PP
自动垂直滚动 
.PP
在文件 SysEdit\&.h 第 64 行定义\&.
.SS "bool HiEasyX::SysEdit::PreStyle::center_text = false"

.PP
文本居中 
.PP
在文件 SysEdit\&.h 第 62 行定义\&.
.SS "bool HiEasyX::SysEdit::PreStyle::hscroll = false"

.PP
拥有水平滚动条 
.PP
在文件 SysEdit\&.h 第 65 行定义\&.
.SS "bool HiEasyX::SysEdit::PreStyle::multiline = false"

.PP
多行文本 
.PP
在文件 SysEdit\&.h 第 61 行定义\&.
.SS "bool HiEasyX::SysEdit::PreStyle::vscroll = false"

.PP
拥有垂直滚动条 
.PP
在文件 SysEdit\&.h 第 63 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
