.TH "HiEasyX::SysComboBox::PreStyle" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysComboBox::PreStyle \- 组合框控件预设样式（必须在创建前设置才有效）  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysComboBox\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "bool \fBalways_show_list\fP = false"
.br
.RI "是否总是显示列表 "
.ti -1c
.RI "bool \fBeditable\fP = false"
.br
.RI "是否可编辑 "
.ti -1c
.RI "bool \fBsort\fP = false"
.br
.RI "是否自动排序 "
.in -1c
.SH "详细描述"
.PP 
组合框控件预设样式（必须在创建前设置才有效） 
.PP
在文件 SysComboBox\&.h 第 42 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "bool HiEasyX::SysComboBox::PreStyle::always_show_list = false"

.PP
是否总是显示列表 
.PP
在文件 SysComboBox\&.h 第 44 行定义\&.
.SS "bool HiEasyX::SysComboBox::PreStyle::editable = false"

.PP
是否可编辑 
.PP
在文件 SysComboBox\&.h 第 45 行定义\&.
.SS "bool HiEasyX::SysComboBox::PreStyle::sort = false"

.PP
是否自动排序 
.PP
在文件 SysComboBox\&.h 第 46 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
