.TH "HiEasyX::SysGroupBox" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysGroupBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysGroupBox\&.h>\fP
.PP
继承自 \fBHiEasyX::SysControlBase\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBSysGroupBox\fP ()"
.br
.ti -1c
.RI "\fBSysGroupBox\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysGroupBox\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.RI "实际调用的创建控件函数（各种控件实现不同，但内部都调用 CreateControl 创建控件） "
.in -1c
.SS "额外继承的成员函数"
.SH "详细描述"
.PP 

.PP
.nf

    系统分组框控件
.fi
.PP
.PP
.PP
.nf
 注意：
    创建控件时不要将此控件作为父控件，否则无法创建控件
.fi
.PP
.PP
\fBBug\fP
.RS 4
分组框背景绘制有 Bug，请斟酌使用 
.RE
.PP

.PP
在文件 SysGroupBox\&.h 第 24 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "HiEasyX::SysGroupBox::SysGroupBox ()"

.PP
在文件 SysGroupBox\&.cpp 第 20 行定义\&.
.PP
.nf
21     {
22     }
.fi
.SS "HiEasyX::SysGroupBox::SysGroupBox (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
在文件 SysGroupBox\&.cpp 第 24 行定义\&.
.PP
.nf
25     {
26         Create(hParent, rct, strText);
27     }
.fi
.SS "HiEasyX::SysGroupBox::SysGroupBox (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
在文件 SysGroupBox\&.cpp 第 29 行定义\&.
.PP
.nf
30     {
31         Create(hParent, x, y, w, h, strText);
32     }
.fi
.SH "成员函数说明"
.PP 
.SS "void HiEasyX::SysGroupBox::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
实际调用的创建控件函数（各种控件实现不同，但内部都调用 CreateControl 创建控件） 
.PP
\fB参数\fP
.RS 4
\fIhParent\fP 父控件句柄 
.RE
.PP

.PP
实现了 \fBHiEasyX::SysControlBase\fP\&.
.PP
在文件 SysGroupBox\&.cpp 第 5 行定义\&.
.PP
.nf
6     {
7         m_type = SCT_GroupBox;
8         m_hWnd = CreateControl(
9             hParent,
10             L"Button",
11             L"",
12             WS_CHILD | WS_VISIBLE | BS_GROUPBOX
13         );
14 
15         HDC hdc = GetDC(m_hWnd);
16         SetBkColor(hdc, RGB(255, 0, 0));
17         ReleaseDC(m_hWnd, hdc);
18     }
.fi


.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
