.TH "HiEasyX::ScrollBar::ScrollBarInfo" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::ScrollBar::ScrollBarInfo \- 滚动条信息  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScrollBar\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "int \fBbtnW\fP"
.br
.ti -1c
.RI "int \fBbtnH\fP"
.br
.RI "普通按钮尺寸 "
.ti -1c
.RI "int \fBslider_free_len\fP"
.br
.RI "滑块可以占据的像素长度 "
.ti -1c
.RI "int \fBslider_move_len\fP"
.br
.RI "滑块顶点可以移动的像素长度 "
.ti -1c
.RI "int \fBslider_len\fP"
.br
.RI "滑块像素长度 "
.in -1c
.SH "详细描述"
.PP 
滚动条信息 
.PP
在文件 ScrollBar\&.h 第 27 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::btnH"

.PP
普通按钮尺寸 
.PP
在文件 ScrollBar\&.h 第 29 行定义\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::btnW"

.PP
在文件 ScrollBar\&.h 第 29 行定义\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_free_len"

.PP
滑块可以占据的像素长度 
.PP
在文件 ScrollBar\&.h 第 30 行定义\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_len"

.PP
滑块像素长度 
.PP
在文件 ScrollBar\&.h 第 32 行定义\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_move_len"

.PP
滑块顶点可以移动的像素长度 
.PP
在文件 ScrollBar\&.h 第 31 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
