.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGif.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGif.h \- \fBHiEasyX\fP 库的动图模块  

.SH SYNOPSIS
.br
.PP
\fC#include <graphics\&.h>\fP
.br
\fC#include <gdiplus\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::Gif\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBHiEasyX\fP 库的动图模块 


.PP
\fB作者\fP
.RS 4
依稀_yixy，huidong（修改） 
.RE
.PP

.PP
在文件 \fBHiGif\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
