.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/HiGUI.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/HiGUI.h \- \fBHiEasyX\fP 库的图形用户界面模块  

.SH SYNOPSIS
.br
.PP
\fC#include 'Page\&.h'\fP
.br
\fC#include 'Static\&.h'\fP
.br
\fC#include 'Button\&.h'\fP
.br
\fC#include 'ProgressCtrl\&.h'\fP
.br
\fC#include 'ScrollBar\&.h'\fP
.br

.SH "详细描述"
.PP 
\fBHiEasyX\fP 库的图形用户界面模块 


.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBHiGUI\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
