.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.h \- \fBHiEasyX\fP 库的图标模块  

.SH SYNOPSIS
.br
.PP
\fC#include <graphics\&.h>\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHIICON_WIDTH\fP   64"
.br
.ti -1c
.RI "#define \fBHIICON_HEIGHT\fP   64"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "DWORD * \fBHiEasyX::GetIconImageBuffer\fP ()"
.br
.RI "获取图标显存 "
.ti -1c
.RI "IMAGE * \fBHiEasyX::GetIconImage\fP ()"
.br
.RI "获取图标对象（显存的拷贝） "
.in -1c
.SH "详细描述"
.PP 
\fBHiEasyX\fP 库的图标模块 


.PP
\fB注解\fP
.RS 4
存储 \fBHiEasyX\fP 图标 
.RE
.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBHiIcon\&.h\fP 中定义\&.
.SH "宏定义说明"
.PP 
.SS "#define HIICON_HEIGHT   64"

.PP
在文件 HiIcon\&.h 第 14 行定义\&.
.SS "#define HIICON_WIDTH   64"

.PP
在文件 HiIcon\&.h 第 13 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
