.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.cpp" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HiIcon\&.h'\fP
.br

.SS "变量"

.in +1c
.ti -1c
.RI "DWORD \fBpBuf\fP [\fBHIICON_WIDTH\fP *\fBHIICON_HEIGHT\fP]"
.br
.in -1c
.SH "变量说明"
.PP 
.SS "DWORD pBuf[\fBHIICON_WIDTH\fP *\fBHIICON_HEIGHT\fP]"

.PP
在文件 HiIcon\&.cpp 第 3 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
