.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiMouseDrag.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiMouseDrag.h \- \fBHiEasyX\fP 库的鼠标拖动处理模块  

.SH SYNOPSIS
.br
.PP
\fC#include <graphics\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::MouseDrag\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBHiEasyX\fP 库的鼠标拖动处理模块 


.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBHiMouseDrag\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
