.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiStart.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiStart.h \- \fBHiEasyX\fP 库的开始界面渲染模块  

.SH SYNOPSIS
.br
.PP
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHiEasyX::RenderStartScene\fP ()"
.br
.RI "渲染开场动画 "
.in -1c
.SH "详细描述"
.PP 
\fBHiEasyX\fP 库的开始界面渲染模块 


.PP
\fB注解\fP
.RS 4
开场动画改编自慢羊羊的《艺术字系列：冰封的 EasyX》 
.RE
.PP
\fB作者\fP
.RS 4
慢羊羊 yw80@qq.com，huidong（改编） 
.RE
.PP

.PP
在文件 \fBHiStart\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
