.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.cpp" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'SysControlBase\&.h'\fP
.br
\fC#include '\&.\&./HiWindow\&.h'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "int \fBHiEasyX::AllocID\fP ()"
.br
.RI "自动分配控件 ID "
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
