.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.h \- HiSysGUI 控件分支：控件基础  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./HiContainer\&.h'\fP
.br
\fC#include <windowsx\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::SysControlBase\fP"
.br
.RI "系统控件基础 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHiEasyX::SysControlType\fP { \fBHiEasyX::SCT_Unknown\fP, \fBHiEasyX::SCT_Group\fP, \fBHiEasyX::SCT_GroupBox\fP, \fBHiEasyX::SCT_Static\fP, \fBHiEasyX::SCT_Button\fP, \fBHiEasyX::SCT_CheckBox\fP, \fBHiEasyX::SCT_RadioButton\fP, \fBHiEasyX::SCT_Edit\fP, \fBHiEasyX::SCT_ComboBox\fP }"
.br
.RI "支持的系统控件类型 "
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "int \fBHiEasyX::AllocID\fP ()"
.br
.RI "自动分配控件 ID "
.in -1c
.SH "详细描述"
.PP 
HiSysGUI 控件分支：控件基础 


.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBSysControlBase\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
