.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysEdit.h" 3 "2023年 一月 13日 星期五" "Version Ver 0.3.0" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysEdit.h \- HiSysGUI 控件分支：输入框  

.SH SYNOPSIS
.br
.PP
\fC#include 'SysControlBase\&.h'\fP
.br
\fC#include <graphics\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::SysEdit\fP"
.br
.RI "系统输入框控件 "
.ti -1c
.RI "struct \fBHiEasyX::SysEdit::PreStyle\fP"
.br
.RI "编辑框预设样式（必须在创建前设置才有效） "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SH "详细描述"
.PP 
HiSysGUI 控件分支：输入框 


.PP
\fB作者\fP
.RS 4
huidong 
.RE
.PP

.PP
在文件 \fBSysEdit\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 HiEasyX 的 源代码自动生成\&.
