.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/ControlBase.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/ControlBase.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./HiContainer\&.h'\fP
.br
\fC#include '\&.\&./HiMacro\&.h'\fP
.br
\fC#include '\&.\&./HiFunc\&.h'\fP
.br
\fC#include '\&.\&./HiCanvas\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::ControlBase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBHiEasyX::MESSAGE_PROC_FUNC\fP) (ControlBase *_Ctrl, int _MsgId, ExMessage _ExMsg)"
.br
.ti -1c
.RI "typedef void(* \fBHiEasyX::MESSAGE_PROC_FUNC_CLASS\fP) (void *_This, ControlBase *_Ctrl, int _MsgId, ExMessage _ExMsg)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHiEasyX::CtrlMessage\fP { \fBHiEasyX::CM_OTHER\fP, \fBHiEasyX::CM_HOVER\fP, \fBHiEasyX::CM_HOVER_OVER\fP, \fBHiEasyX::CM_PRESS\fP, \fBHiEasyX::CM_PRESS_OVER\fP, \fBHiEasyX::CM_CLICK\fP, \fBHiEasyX::CM_DOUBLE_CLICK\fP, \fBHiEasyX::CM_FOCUS\fP, \fBHiEasyX::CM_FOCUS_OVER\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
