.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX Directory Reference" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBHiGUI\fP"
.br
.ti -1c
.RI "directory \fBHiSysGUI\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHiCanvas\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiCanvas\&.h\fP"
.br
.ti -1c
.RI "file \fBHiContainer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiContainer\&.h\fP"
.br
.ti -1c
.RI "file \fBHiDef\&.h\fP"
.br
.ti -1c
.RI "file \fBHiDrawingProperty\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiDrawingProperty\&.h\fP"
.br
.ti -1c
.RI "file \fBHiFPS\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiFPS\&.h\fP"
.br
.ti -1c
.RI "file \fBHiFunc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiFunc\&.h\fP"
.br
.ti -1c
.RI "file \fBHiGif\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiGif\&.h\fP"
.br
.ti -1c
.RI "file \fBHiIcon\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiIcon\&.h\fP"
.br
.ti -1c
.RI "file \fBHiMacro\&.h\fP"
.br
.ti -1c
.RI "file \fBHiMouseDrag\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiMouseDrag\&.h\fP"
.br
.ti -1c
.RI "file \fBHiMusicMCI\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiMusicMCI\&.h\fP"
.br
.ti -1c
.RI "file \fBHiStart\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiStart\&.h\fP"
.br
.ti -1c
.RI "file \fBHiWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHiWindow\&.h\fP"
.br
.in -1c
