.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX Directory Reference" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBHiEasyX\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHiEasyX\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
