.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiDef.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiDef.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_HIEASYX_VER_STR_\fP   L'Ver 0\&.2 (alpha)'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _HIEASYX_VER_STR_   L'Ver 0\&.2 (alpha)'"

.PP
Definition at line 8 of file HiDef\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
