.TH "HiEasyX::SysEdit" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysEdit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysEdit\&.h>\fP
.PP
Inherits \fBHiEasyX::SysControlBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysEdit\fP ()"
.br
.ti -1c
.RI "\fBSysEdit\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysEdit\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fB~SysEdit\fP () override"
.br
.ti -1c
.RI "void \fBPreSetStyle\fP (bool multiline, bool center_text=false, bool vscroll=false, bool auto_vscroll=false, bool hscroll=false, bool auto_hscroll=false)"
.br
.ti -1c
.RI "LRESULT \fBUpdateMessage\fP (UINT msg, WPARAM wParam, LPARAM lParam, bool &bRet) override"
.br
.ti -1c
.RI "void \fBRegisterMessage\fP (void(*pFunc)(std::wstring wstrText))"
.br
.ti -1c
.RI "void \fBRightAlign\fP (bool enable)"
.br
.ti -1c
.RI "void \fBUppercase\fP (bool enable)"
.br
.ti -1c
.RI "void \fBLowercase\fP (bool enable)"
.br
.ti -1c
.RI "void \fBPassword\fP (bool enable)"
.br
.ti -1c
.RI "void \fBReadOnly\fP (bool enable)"
.br
.ti -1c
.RI "void \fBNumberOnly\fP (bool enable)"
.br
.ti -1c
.RI "int \fBGetMaxTextLength\fP ()"
.br
.ti -1c
.RI "void \fBSetMaxTextLength\fP (int len)"
.br
.ti -1c
.RI "void \fBSetBkColor\fP (COLORREF color)"
.br
.ti -1c
.RI "void \fBSetTextBkColor\fP (COLORREF color)"
.br
.ti -1c
.RI "void \fBSetTextColor\fP (COLORREF color)"
.br
.ti -1c
.RI "void \fBGetSel\fP (int *begin, int *end)"
.br
.ti -1c
.RI "void \fBSetSel\fP (int begin, int end)"
.br
.ti -1c
.RI "void \fBCopy\fP ()"
.br
.ti -1c
.RI "void \fBCut\fP ()"
.br
.ti -1c
.RI "void \fBPaste\fP ()"
.br
.ti -1c
.RI "void \fBDelete\fP ()"
.br
.ti -1c
.RI "void \fBReplace\fP (std::wstring wstrText)"
.br
.ti -1c
.RI "bool \fBisEdited\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file SysEdit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::SysEdit::SysEdit ()"

.PP
Definition at line 21 of file SysEdit\&.cpp\&.
.SS "HiEasyX::SysEdit::SysEdit (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 25 of file SysEdit\&.cpp\&.
.SS "HiEasyX::SysEdit::SysEdit (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 30 of file SysEdit\&.cpp\&.
.SS "HiEasyX::SysEdit::~SysEdit ()\fC [override]\fP"

.PP
Definition at line 35 of file SysEdit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::SysEdit::Copy ()"

.PP
Definition at line 197 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Cut ()"

.PP
Definition at line 202 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Delete ()"

.PP
Definition at line 212 of file SysEdit\&.cpp\&.
.SS "int HiEasyX::SysEdit::GetMaxTextLength ()"

.PP
Definition at line 156 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::GetSel (int * begin, int * end)"

.PP
Definition at line 187 of file SysEdit\&.cpp\&.
.SS "bool HiEasyX::SysEdit::isEdited ()"

.PP
Definition at line 222 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Lowercase (bool enable)"

.PP
Definition at line 131 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::NumberOnly (bool enable)"

.PP
Definition at line 150 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Password (bool enable)"

.PP
Definition at line 138 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Paste ()"

.PP
Definition at line 207 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::PreSetStyle (bool multiline, bool center_text = \fCfalse\fP, bool vscroll = \fCfalse\fP, bool auto_vscroll = \fCfalse\fP, bool hscroll = \fCfalse\fP, bool auto_hscroll = \fCfalse\fP)"

.PP
Definition at line 41 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::ReadOnly (bool enable)"

.PP
Definition at line 144 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 5 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::RegisterMessage (void(*)(std::wstring wstrText) pFunc)"

.PP
Definition at line 89 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Replace (std::wstring wstrText)"

.PP
Definition at line 217 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::RightAlign (bool enable)"

.PP
Definition at line 117 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::SetBkColor (COLORREF color)"

.PP
Definition at line 166 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::SetMaxTextLength (int len)"

.PP
Definition at line 161 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::SetSel (int begin, int end)"

.PP
Definition at line 192 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::SetTextBkColor (COLORREF color)"

.PP
Definition at line 175 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::SetTextColor (COLORREF color)"

.PP
Definition at line 181 of file SysEdit\&.cpp\&.
.SS "LRESULT HiEasyX::SysEdit::UpdateMessage (UINT msg, WPARAM wParam, LPARAM lParam, bool & bRet)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 53 of file SysEdit\&.cpp\&.
.SS "void HiEasyX::SysEdit::Uppercase (bool enable)"

.PP
Definition at line 124 of file SysEdit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
