.TH "HiEasyX::MusicMCI" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::MusicMCI
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiMusicMCI\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMusicMCI\fP () noexcept"
.br
.ti -1c
.RI "virtual \fB~MusicMCI\fP ()"
.br
.ti -1c
.RI "bool \fBopen\fP (LPCWSTR music) noexcept"
.br
.ti -1c
.RI "bool \fBplay\fP () noexcept"
.br
.ti -1c
.RI "bool \fBpause\fP () noexcept"
.br
.ti -1c
.RI "bool \fBstop\fP () noexcept"
.br
.ti -1c
.RI "bool \fBclose\fP () noexcept"
.br
.ti -1c
.RI "bool \fBgetCurrentTime\fP (DWORD &pos) noexcept"
.br
.ti -1c
.RI "bool \fBgetTotalTime\fP (DWORD &time) noexcept"
.br
.ti -1c
.RI "bool \fBsetVolume\fP (size_t volume) noexcept"
.br
.ti -1c
.RI "bool \fBsetStartTime\fP (size_t start) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file HiMusicMCI\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::MusicMCI::MusicMCI ()\fC [noexcept]\fP"

.PP
Definition at line 16 of file HiMusicMCI\&.cpp\&.
.SS "HiEasyX::MusicMCI::~MusicMCI ()\fC [virtual]\fP"

.PP
Definition at line 21 of file HiMusicMCI\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HiEasyX::MusicMCI::close ()\fC [noexcept]\fP"

.PP
Definition at line 94 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::getCurrentTime (DWORD & pos)\fC [noexcept]\fP"

.PP
Definition at line 111 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::getTotalTime (DWORD & time)\fC [noexcept]\fP"

.PP
Definition at line 132 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::open (LPCWSTR music)\fC [noexcept]\fP"

.PP
Definition at line 28 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::pause ()\fC [noexcept]\fP"

.PP
Definition at line 66 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::play ()\fC [noexcept]\fP"

.PP
Definition at line 52 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::setStartTime (size_t start)\fC [noexcept]\fP"

.PP
Definition at line 177 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::setVolume (size_t volume)\fC [noexcept]\fP"

.PP
Definition at line 153 of file HiMusicMCI\&.cpp\&.
.SS "bool HiEasyX::MusicMCI::stop ()\fC [noexcept]\fP"

.PP
Definition at line 80 of file HiMusicMCI\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
