.TH "HiEasyX::MouseDrag" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::MouseDrag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiMouseDrag\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateMessage\fP (ExMessage m)"
.br
.ti -1c
.RI "bool \fBisLeftDrag\fP ()"
.br
.ti -1c
.RI "bool \fBisMiddleDrag\fP ()"
.br
.ti -1c
.RI "bool \fBisRightDrag\fP ()"
.br
.ti -1c
.RI "int \fBGetDragX\fP ()"
.br
.ti -1c
.RI "int \fBGetDragY\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file HiMouseDrag\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int HiEasyX::MouseDrag::GetDragX ()"

.PP
Definition at line 77 of file HiMouseDrag\&.cpp\&.
.SS "int HiEasyX::MouseDrag::GetDragY ()"

.PP
Definition at line 82 of file HiMouseDrag\&.cpp\&.
.SS "bool HiEasyX::MouseDrag::isLeftDrag ()"

.PP
Definition at line 56 of file HiMouseDrag\&.cpp\&.
.SS "bool HiEasyX::MouseDrag::isMiddleDrag ()"

.PP
Definition at line 63 of file HiMouseDrag\&.cpp\&.
.SS "bool HiEasyX::MouseDrag::isRightDrag ()"

.PP
Definition at line 70 of file HiMouseDrag\&.cpp\&.
.SS "void HiEasyX::MouseDrag::UpdateMessage (ExMessage m)"

.PP
Definition at line 47 of file HiMouseDrag\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
