.TH "HiEasyX::Layer" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::Layer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiCanvas\&.h>\fP
.PP
Inherits list< ImageBlock * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRender\fP (IMAGE *pImg=nullptr, bool bShowOutline=false, bool bShowText=true, std::wstring wstrAddedText=L'')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBbVisible\fP = true"
.br
.ti -1c
.RI "BYTE \fBalpha\fP = 255"
.br
.ti -1c
.RI "bool \fBbOutline\fP = false"
.br
.ti -1c
.RI "bool \fBbText\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 550 of file HiCanvas\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::Layer::Render (IMAGE * pImg = \fCnullptr\fP, bool bShowOutline = \fCfalse\fP, bool bShowText = \fCtrue\fP, std::wstring wstrAddedText = \fCL''\fP)"

.PP
Definition at line 1660 of file HiCanvas\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "BYTE HiEasyX::Layer::alpha = 255"

.PP
Definition at line 557 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::Layer::bOutline = false"

.PP
Definition at line 558 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::Layer::bText = false"

.PP
Definition at line 559 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::Layer::bVisible = true"

.PP
Definition at line 556 of file HiCanvas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
