.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX.h
.SH SYNOPSIS
.br
.PP
\fC#include 'HiEasyX/HiDef\&.h'\fP
.br
\fC#include 'HiEasyX/HiMacro\&.h'\fP
.br
\fC#include 'HiEasyX/HiFunc\&.h'\fP
.br
\fC#include 'HiEasyX/HiFPS\&.h'\fP
.br
\fC#include 'HiEasyX/HiDrawingProperty\&.h'\fP
.br
\fC#include 'HiEasyX/HiMouseDrag\&.h'\fP
.br
\fC#include 'HiEasyX/HiMusicMCI\&.h'\fP
.br
\fC#include 'HiEasyX/HiGif\&.h'\fP
.br
\fC#include 'HiEasyX/HiWindow\&.h'\fP
.br
\fC#include 'HiEasyX/HiSysGUI/HiSysGUI\&.h'\fP
.br
\fC#include 'HiEasyX/HiCanvas\&.h'\fP
.br
\fC#include 'HiEasyX/HiGUI/HiGUI\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HIEASYX_H__\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __HIEASYX_H__"

.PP
Definition at line 17 of file HiEasyX\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
