.TH "HiEasyX::ImageBlock" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::ImageBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiCanvas\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageBlock\fP ()"
.br
.ti -1c
.RI "\fBImageBlock\fP (\fBCanvas\fP *pCanvas)"
.br
.ti -1c
.RI "\fBImageBlock\fP (int _x, int _y, \fBCanvas\fP *pCanvas)"
.br
.ti -1c
.RI "\fBImageBlock\fP (int _x, int _y, int w, int h, COLORREF cBk=0)"
.br
.ti -1c
.RI "virtual \fB~ImageBlock\fP ()"
.br
.ti -1c
.RI "\fBCanvas\fP * \fBCreateCanvas\fP (int w, int h, COLORREF cBk=0)"
.br
.ti -1c
.RI "\fBCanvas\fP * \fBGetCanvas\fP () const"
.br
.ti -1c
.RI "void \fBSetCanvas\fP (\fBCanvas\fP *pCanvas)"
.br
.ti -1c
.RI "int \fBGetWidth\fP () const"
.br
.ti -1c
.RI "int \fBGetHeight\fP () const"
.br
.ti -1c
.RI "POINT \fBGetPos\fP () const"
.br
.ti -1c
.RI "void \fBSetPos\fP (int _x, int _y)"
.br
.ti -1c
.RI "virtual void \fBRender\fP (IMAGE *pImg, BYTE \fBalpha\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP = 0"
.br
.ti -1c
.RI "int \fBy\fP = 0"
.br
.ti -1c
.RI "RECT \fBrctCrop\fP = { 0 }"
.br
.ti -1c
.RI "bool \fBbUseSrcAlpha\fP = false"
.br
.ti -1c
.RI "bool \fBisAlphaCalculated\fP = false"
.br
.ti -1c
.RI "BYTE \fBalpha\fP = 255"
.br
.ti -1c
.RI "bool \fBbVisible\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 499 of file HiCanvas\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::ImageBlock::ImageBlock ()"

.PP
Definition at line 1591 of file HiCanvas\&.cpp\&.
.SS "HiEasyX::ImageBlock::ImageBlock (\fBCanvas\fP * pCanvas)"

.PP
Definition at line 1595 of file HiCanvas\&.cpp\&.
.SS "HiEasyX::ImageBlock::ImageBlock (int _x, int _y, \fBCanvas\fP * pCanvas)"

.PP
Definition at line 1600 of file HiCanvas\&.cpp\&.
.SS "HiEasyX::ImageBlock::ImageBlock (int _x, int _y, int w, int h, COLORREF cBk = \fC0\fP)"

.PP
Definition at line 1607 of file HiCanvas\&.cpp\&.
.SS "HiEasyX::ImageBlock::~ImageBlock ()\fC [virtual]\fP"

.PP
Definition at line 1614 of file HiCanvas\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCanvas\fP * HiEasyX::ImageBlock::CreateCanvas (int w, int h, COLORREF cBk = \fC0\fP)"

.PP
Definition at line 1619 of file HiCanvas\&.cpp\&.
.SS "\fBCanvas\fP* HiEasyX::ImageBlock::GetCanvas () const\fC [inline]\fP"

.PP
Definition at line 532 of file HiCanvas\&.h\&.
.SS "int HiEasyX::ImageBlock::GetHeight () const\fC [inline]\fP"

.PP
Definition at line 538 of file HiCanvas\&.h\&.
.SS "POINT HiEasyX::ImageBlock::GetPos () const\fC [inline]\fP"

.PP
Definition at line 540 of file HiCanvas\&.h\&.
.SS "int HiEasyX::ImageBlock::GetWidth () const\fC [inline]\fP"

.PP
Definition at line 536 of file HiCanvas\&.h\&.
.SS "void HiEasyX::ImageBlock::Render (IMAGE * pImg, BYTE alpha)\fC [virtual]\fP"

.PP
Definition at line 1646 of file HiCanvas\&.cpp\&.
.SS "void HiEasyX::ImageBlock::SetCanvas (\fBCanvas\fP * pCanvas)"

.PP
Definition at line 1634 of file HiCanvas\&.cpp\&.
.SS "void HiEasyX::ImageBlock::SetPos (int _x, int _y)"

.PP
Definition at line 1640 of file HiCanvas\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "BYTE HiEasyX::ImageBlock::alpha = 255"

.PP
Definition at line 515 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::ImageBlock::bUseSrcAlpha = false"

.PP
Definition at line 510 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::ImageBlock::bVisible = true"

.PP
Definition at line 516 of file HiCanvas\&.h\&.
.SS "bool HiEasyX::ImageBlock::isAlphaCalculated = false"

.PP
Definition at line 512 of file HiCanvas\&.h\&.
.SS "RECT HiEasyX::ImageBlock::rctCrop = { 0 }"

.PP
Definition at line 509 of file HiCanvas\&.h\&.
.SS "int HiEasyX::ImageBlock::x = 0"

.PP
Definition at line 508 of file HiCanvas\&.h\&.
.SS "int HiEasyX::ImageBlock::y = 0"

.PP
Definition at line 508 of file HiCanvas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
