.TH "HiEasyX::ScrollBar" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::ScrollBar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScrollBar\&.h>\fP
.PP
Inherits \fBHiEasyX::ControlBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBScrollBarInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScrollBar\fP ()"
.br
.ti -1c
.RI "\fBScrollBar\fP (int x, int y, int w, int h, int len, int pos, bool bHorizontal=false)"
.br
.ti -1c
.RI "int \fBGetButtonHeight\fP () const"
.br
.ti -1c
.RI "void \fBSetButtonHeight\fP (int h)"
.br
.ti -1c
.RI "int \fBGetButtonWidth\fP () const"
.br
.ti -1c
.RI "void \fBSetButtonWidth\fP (int w)"
.br
.ti -1c
.RI "bool \fBisDragging\fP () const"
.br
.ti -1c
.RI "int \fBGetSliderLength\fP () const"
.br
.ti -1c
.RI "int \fBGetSliderContentPos\fP () const"
.br
.ti -1c
.RI "void \fBSetSliderContentPos\fP (float pos)"
.br
.ti -1c
.RI "void \fBMoveSlider\fP (float d)"
.br
.ti -1c
.RI "int \fBGetContentLength\fP () const"
.br
.ti -1c
.RI "void \fBSetContentLength\fP (int len)"
.br
.ti -1c
.RI "int \fBGetViewLength\fP () const"
.br
.ti -1c
.RI "void \fBSetViewLength\fP (int len)"
.br
.ti -1c
.RI "int \fBGetSliderSpeed\fP () const"
.br
.ti -1c
.RI "void \fBSetSliderSpeed\fP (int speed)"
.br
.ti -1c
.RI "bool \fBisHorizontal\fP () const"
.br
.ti -1c
.RI "void \fBEnableHorizontal\fP (bool enable)"
.br
.ti -1c
.RI "bool \fBisSliderPosChanged\fP ()"
.br
.ti -1c
.RI "RECT \fBGetOnWheelRect\fP () const"
.br
.ti -1c
.RI "void \fBSetOnWheelRect\fP (RECT rct)"
.br
.ti -1c
.RI "void \fBUpdateRect\fP (RECT rctOld) override"
.br
.ti -1c
.RI "void \fBUpdateMessage\fP (ExMessage msg) override"
.br
.ti -1c
.RI "void \fBDraw\fP (bool draw_child=true) override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnNormalButtonMsg\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdateSliderRect\fP ()"
.br
.ti -1c
.RI "void \fBUpdatePosRatio\fP ()"
.br
.ti -1c
.RI "void \fBUpdateViewRatio\fP ()"
.br
.ti -1c
.RI "void \fBUpdateScrollBarInfo\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOnSpecialButtonMsg\fP (void *pThis, \fBControlBase\fP *pCtrl, int msgid, ExMessage msg)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBm_nBtnHeight\fP = 20"
.br
.ti -1c
.RI "int \fBm_nBtnWidth\fP = 20"
.br
.ti -1c
.RI "bool \fBm_bHorizontal\fP = false"
.br
.ti -1c
.RI "int \fBm_nDrawInterval\fP = 6"
.br
.ti -1c
.RI "\fBButton\fP \fBm_btnTop\fP"
.br
.ti -1c
.RI "\fBButton\fP \fBm_btnUp\fP"
.br
.ti -1c
.RI "\fBButton\fP \fBm_btnDown\fP"
.br
.ti -1c
.RI "\fBButton\fP \fBm_btnBottom\fP"
.br
.ti -1c
.RI "\fBButton\fP \fBm_btnDrag\fP"
.br
.ti -1c
.RI "\fBMouseDrag\fP \fBm_MouseDrag\fP"
.br
.ti -1c
.RI "bool \fBm_bDragging\fP = false"
.br
.ti -1c
.RI "int \fBm_nSliderSpeed\fP = 20"
.br
.ti -1c
.RI "clock_t \fBm_tPressed\fP = 0"
.br
.ti -1c
.RI "float \fBm_fPos\fP = 0"
.br
.ti -1c
.RI "int \fBm_nLen\fP = 0"
.br
.ti -1c
.RI "float \fBm_fPosRatio\fP = 0"
.br
.ti -1c
.RI "\fBScrollBarInfo\fP \fBm_info\fP = {}"
.br
.ti -1c
.RI "int \fBm_nViewLen\fP = 10"
.br
.ti -1c
.RI "float \fBm_fViewRatio\fP = 1"
.br
.ti -1c
.RI "bool \fBm_bSliderPosChanged\fP = false"
.br
.ti -1c
.RI "RECT \fBm_rctOnWheel\fP = { 0 }"
.br
.ti -1c
.RI "bool \fBm_bSetOnWheelRct\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file ScrollBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::ScrollBar::ScrollBar ()"

.PP
Definition at line 141 of file ScrollBar\&.cpp\&.
.SS "HiEasyX::ScrollBar::ScrollBar (int x, int y, int w, int h, int len, int pos, bool bHorizontal = \fCfalse\fP)"

.PP
Definition at line 146 of file ScrollBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::ScrollBar::Draw (bool draw_child = \fCtrue\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::ControlBase\fP\&.
.PP
Definition at line 272 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::EnableHorizontal (bool enable)"

.PP
Definition at line 370 of file ScrollBar\&.cpp\&.
.SS "int HiEasyX::ScrollBar::GetButtonHeight () const\fC [inline]\fP"

.PP
Definition at line 92 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetButtonWidth () const\fC [inline]\fP"

.PP
Definition at line 97 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetContentLength () const\fC [inline]\fP"

.PP
Definition at line 118 of file ScrollBar\&.h\&.
.SS "RECT HiEasyX::ScrollBar::GetOnWheelRect () const\fC [inline]\fP"

.PP
Definition at line 142 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetSliderContentPos () const\fC [inline]\fP"

.PP
Definition at line 109 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetSliderLength () const\fC [inline]\fP"

.PP
Definition at line 106 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetSliderSpeed () const\fC [inline]\fP"

.PP
Definition at line 128 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::GetViewLength () const\fC [inline]\fP"

.PP
Definition at line 123 of file ScrollBar\&.h\&.
.SS "void HiEasyX::ScrollBar::Init ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 54 of file ScrollBar\&.cpp\&.
.SS "bool HiEasyX::ScrollBar::isDragging () const\fC [inline]\fP"

.PP
Definition at line 103 of file ScrollBar\&.h\&.
.SS "bool HiEasyX::ScrollBar::isHorizontal () const\fC [inline]\fP"

.PP
Definition at line 133 of file ScrollBar\&.h\&.
.SS "bool HiEasyX::ScrollBar::isSliderPosChanged ()"

.PP
Definition at line 357 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::MoveSlider (float d)"

.PP
Definition at line 173 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::OnNormalButtonMsg ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 24 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::OnSpecialButtonMsg (void * pThis, \fBControlBase\fP * pCtrl, int msgid, ExMessage msg)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetButtonHeight (int h)"

.PP
Definition at line 127 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetButtonWidth (int w)"

.PP
Definition at line 134 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetContentLength (int len)"

.PP
Definition at line 178 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetOnWheelRect (RECT rct)"

.PP
Definition at line 364 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetSliderContentPos (float pos)"

.PP
Definition at line 155 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetSliderSpeed (int speed)"

.PP
Definition at line 193 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::SetViewLength (int len)"

.PP
Definition at line 186 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdateMessage (ExMessage msg)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::ControlBase\fP\&.
.PP
Definition at line 222 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdatePosRatio ()\fC [protected]\fP"

.PP
Definition at line 82 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdateRect (RECT rctOld)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::ControlBase\fP\&.
.PP
Definition at line 198 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdateScrollBarInfo ()\fC [protected]\fP"

.PP
Definition at line 107 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdateSliderRect ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 68 of file ScrollBar\&.cpp\&.
.SS "void HiEasyX::ScrollBar::UpdateViewRatio ()\fC [protected]\fP"

.PP
Definition at line 94 of file ScrollBar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool HiEasyX::ScrollBar::m_bDragging = false\fC [protected]\fP"

.PP
Definition at line 47 of file ScrollBar\&.h\&.
.SS "bool HiEasyX::ScrollBar::m_bHorizontal = false\fC [protected]\fP"

.PP
Definition at line 36 of file ScrollBar\&.h\&.
.SS "bool HiEasyX::ScrollBar::m_bSetOnWheelRct = false\fC [protected]\fP"

.PP
Definition at line 63 of file ScrollBar\&.h\&.
.SS "bool HiEasyX::ScrollBar::m_bSliderPosChanged = false\fC [protected]\fP"

.PP
Definition at line 60 of file ScrollBar\&.h\&.
.SS "\fBButton\fP HiEasyX::ScrollBar::m_btnBottom\fC [protected]\fP"

.PP
Definition at line 44 of file ScrollBar\&.h\&.
.SS "\fBButton\fP HiEasyX::ScrollBar::m_btnDown\fC [protected]\fP"

.PP
Definition at line 43 of file ScrollBar\&.h\&.
.SS "\fBButton\fP HiEasyX::ScrollBar::m_btnDrag\fC [protected]\fP"

.PP
Definition at line 45 of file ScrollBar\&.h\&.
.SS "\fBButton\fP HiEasyX::ScrollBar::m_btnTop\fC [protected]\fP"

.PP
Definition at line 41 of file ScrollBar\&.h\&.
.SS "\fBButton\fP HiEasyX::ScrollBar::m_btnUp\fC [protected]\fP"

.PP
Definition at line 42 of file ScrollBar\&.h\&.
.SS "float HiEasyX::ScrollBar::m_fPos = 0\fC [protected]\fP"

.PP
Definition at line 51 of file ScrollBar\&.h\&.
.SS "float HiEasyX::ScrollBar::m_fPosRatio = 0\fC [protected]\fP"

.PP
Definition at line 53 of file ScrollBar\&.h\&.
.SS "float HiEasyX::ScrollBar::m_fViewRatio = 1\fC [protected]\fP"

.PP
Definition at line 58 of file ScrollBar\&.h\&.
.SS "\fBScrollBarInfo\fP HiEasyX::ScrollBar::m_info = {}\fC [protected]\fP"

.PP
Definition at line 55 of file ScrollBar\&.h\&.
.SS "\fBMouseDrag\fP HiEasyX::ScrollBar::m_MouseDrag\fC [protected]\fP"

.PP
Definition at line 46 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nBtnHeight = 20\fC [protected]\fP"

.PP
Definition at line 33 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nBtnWidth = 20\fC [protected]\fP"

.PP
Definition at line 34 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nDrawInterval = 6\fC [protected]\fP"

.PP
Definition at line 38 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nLen = 0\fC [protected]\fP"

.PP
Definition at line 52 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nSliderSpeed = 20\fC [protected]\fP"

.PP
Definition at line 48 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::m_nViewLen = 10\fC [protected]\fP"

.PP
Definition at line 57 of file ScrollBar\&.h\&.
.SS "RECT HiEasyX::ScrollBar::m_rctOnWheel = { 0 }\fC [protected]\fP"

.PP
Definition at line 62 of file ScrollBar\&.h\&.
.SS "clock_t HiEasyX::ScrollBar::m_tPressed = 0\fC [protected]\fP"

.PP
Definition at line 49 of file ScrollBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
