.TH "HiEasyX::SysCheckBox" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysCheckBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysCheckBox\&.h>\fP
.PP
Inherits \fBHiEasyX::SysControlBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysCheckBox\fP ()"
.br
.ti -1c
.RI "\fBSysCheckBox\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysCheckBox\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.ti -1c
.RI "LRESULT \fBUpdateMessage\fP (UINT msg, WPARAM wParam, LPARAM lParam, bool &bRet) override"
.br
.ti -1c
.RI "void \fBRegisterMessage\fP (void(*pFunc)(bool checked))"
.br
.ti -1c
.RI "bool \fBisChecked\fP () const"
.br
.ti -1c
.RI "void \fBCheck\fP (bool check)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file SysCheckBox\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::SysCheckBox::SysCheckBox ()"

.PP
Definition at line 16 of file SysCheckBox\&.cpp\&.
.SS "HiEasyX::SysCheckBox::SysCheckBox (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 20 of file SysCheckBox\&.cpp\&.
.SS "HiEasyX::SysCheckBox::SysCheckBox (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 25 of file SysCheckBox\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::SysCheckBox::Check (bool check)"

.PP
Definition at line 51 of file SysCheckBox\&.cpp\&.
.SS "bool HiEasyX::SysCheckBox::isChecked () const\fC [inline]\fP"

.PP
Definition at line 37 of file SysCheckBox\&.h\&.
.SS "void HiEasyX::SysCheckBox::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 5 of file SysCheckBox\&.cpp\&.
.SS "void HiEasyX::SysCheckBox::RegisterMessage (void(*)(bool checked) pFunc)"

.PP
Definition at line 46 of file SysCheckBox\&.cpp\&.
.SS "LRESULT HiEasyX::SysCheckBox::UpdateMessage (UINT msg, WPARAM wParam, LPARAM lParam, bool & bRet)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 30 of file SysCheckBox\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
