.TH "HiEasyX::Window" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::Window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiWindow\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP ()"
.br
.ti -1c
.RI "\fBWindow\fP (int w, int h, int flag=\fBEW_NORMAL\fP, LPCTSTR lpszWndTitle=L'', WNDPROC WindowProcess=nullptr, HWND hParent=nullptr)"
.br
.ti -1c
.RI "virtual \fB~Window\fP ()"
.br
.ti -1c
.RI "HWND \fBInitWindow\fP (int w=640, int h=480, int flag=\fBEW_NORMAL\fP, LPCTSTR lpszWndTitle=L'', WNDPROC WindowProcess=nullptr, HWND hParent=nullptr)"
.br
.ti -1c
.RI "HWND \fBCreate\fP (int w=640, int h=480, int flag=\fBEW_NORMAL\fP, LPCTSTR lpszWndTitle=L'', WNDPROC WindowProcess=nullptr, HWND hParent=nullptr)"
.br
.ti -1c
.RI "void \fBCloseWindow\fP ()"
.br
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.ti -1c
.RI "void \fBSetProcFunc\fP (WNDPROC WindowProcess)"
.br
.ti -1c
.RI "HWND \fBGetHandle\fP ()"
.br
.ti -1c
.RI "\fBEasyWindow\fP \fBGetInfo\fP ()"
.br
.ti -1c
.RI "bool \fBisAlive\fP ()"
.br
.ti -1c
.RI "IMAGE * \fBGetImage\fP ()"
.br
.ti -1c
.RI "\fBCanvas\fP * \fBGetCanvas\fP ()"
.br
.ti -1c
.RI "void \fBBindCanvas\fP (\fBCanvas\fP *pCanvas)"
.br
.ti -1c
.RI "void \fBWaitMyTask\fP ()"
.br
.ti -1c
.RI "bool \fBSetWorkingWindow\fP ()"
.br
.ti -1c
.RI "void \fBSetQuickDraw\fP (UINT nSkipPixels)"
.br
.ti -1c
.RI "void \fBFlushDrawing\fP ()"
.br
.ti -1c
.RI "void \fBRedraw\fP ()"
.br
.ti -1c
.RI "bool \fBBeginTask\fP ()"
.br
.ti -1c
.RI "void \fBEndTask\fP (bool flush=true)"
.br
.ti -1c
.RI "bool \fBisInTask\fP ()"
.br
.ti -1c
.RI "bool \fBisSizeChanged\fP ()"
.br
.ti -1c
.RI "void \fBCreateTray\fP (LPCTSTR lpszTrayName)"
.br
.ti -1c
.RI "void \fBDeleteTray\fP ()"
.br
.ti -1c
.RI "void \fBSetTrayMenu\fP (HMENU hMenu)"
.br
.ti -1c
.RI "void \fBSetTrayMenuProcFunc\fP (void(*pFunc)(UINT))"
.br
.ti -1c
.RI "void \fBPreSetStyle\fP (long lStyle)"
.br
.ti -1c
.RI "void \fBPreSetPos\fP (int x, int y)"
.br
.ti -1c
.RI "long \fBGetStyle\fP ()"
.br
.ti -1c
.RI "int \fBSetStyle\fP (long lNewStyle)"
.br
.ti -1c
.RI "long \fBGetExStyle\fP ()"
.br
.ti -1c
.RI "int \fBSetExStyle\fP (long lNewExStyle)"
.br
.ti -1c
.RI "POINT \fBGetPos\fP ()"
.br
.ti -1c
.RI "SIZE \fBGetWindowSize\fP ()"
.br
.ti -1c
.RI "int \fBGetWindowWidth\fP ()"
.br
.ti -1c
.RI "int \fBGetWindowHeight\fP ()"
.br
.ti -1c
.RI "int \fBGetClientWidth\fP ()"
.br
.ti -1c
.RI "int \fBGetClientHeight\fP ()"
.br
.ti -1c
.RI "void \fBMove\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBMoveRel\fP (int dx, int dy)"
.br
.ti -1c
.RI "void \fBResize\fP (int w, int h)"
.br
.ti -1c
.RI "bool \fBisForegroundWindow\fP ()"
.br
.ti -1c
.RI "ExMessage \fBGet_Message\fP (BYTE filter=\-1)"
.br
.ti -1c
.RI "void \fBGet_Message\fP (ExMessage *msg, BYTE filter=\-1)"
.br
.ti -1c
.RI "bool \fBPeek_Message\fP (ExMessage *msg, BYTE filter=\-1, bool removemsg=true)"
.br
.ti -1c
.RI "void \fBFlush_Message\fP (BYTE filter=\-1)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file HiWindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::Window::Window ()"

.PP
Definition at line 1523 of file HiWindow\&.cpp\&.
.SS "HiEasyX::Window::Window (int w, int h, int flag = \fC\fBEW_NORMAL\fP\fP, LPCTSTR lpszWndTitle = \fCL''\fP, WNDPROC WindowProcess = \fCnullptr\fP, HWND hParent = \fCnullptr\fP)"

.PP
Definition at line 1527 of file HiWindow\&.cpp\&.
.SS "HiEasyX::Window::~Window ()\fC [virtual]\fP"

.PP
Definition at line 1532 of file HiWindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HiEasyX::Window::BeginTask ()"

.PP
Definition at line 1609 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::BindCanvas (\fBCanvas\fP * pCanvas)"

.PP
Definition at line 1594 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::CloseWindow ()"

.PP
Definition at line 1554 of file HiWindow\&.cpp\&.
.SS "HWND HiEasyX::Window::Create (int w = \fC640\fP, int h = \fC480\fP, int flag = \fC\fBEW_NORMAL\fP\fP, LPCTSTR lpszWndTitle = \fCL''\fP, WNDPROC WindowProcess = \fCnullptr\fP, HWND hParent = \fCnullptr\fP)"

.PP
Definition at line 1549 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::CreateTray (LPCTSTR lpszTrayName)"

.PP
Definition at line 1636 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::DeleteTray ()"

.PP
Definition at line 1641 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Destroy ()"

.PP
Definition at line 1559 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::EndTask (bool flush = \fCtrue\fP)"

.PP
Definition at line 1621 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Flush_Message (BYTE filter = \fC\-1\fP)"

.PP
Definition at line 1769 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::FlushDrawing ()"

.PP
Definition at line 1673 of file HiWindow\&.cpp\&.
.SS "ExMessage HiEasyX::Window::Get_Message (BYTE filter = \fC\-1\fP)"

.PP
Definition at line 1754 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Get_Message (ExMessage * msg, BYTE filter = \fC\-1\fP)"

.PP
Definition at line 1759 of file HiWindow\&.cpp\&.
.SS "\fBCanvas\fP * HiEasyX::Window::GetCanvas ()"

.PP
Definition at line 1589 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::GetClientHeight ()"

.PP
Definition at line 1749 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::GetClientWidth ()"

.PP
Definition at line 1744 of file HiWindow\&.cpp\&.
.SS "long HiEasyX::Window::GetExStyle ()"

.PP
Definition at line 1694 of file HiWindow\&.cpp\&.
.SS "HWND HiEasyX::Window::GetHandle ()"

.PP
Definition at line 1569 of file HiWindow\&.cpp\&.
.SS "IMAGE * HiEasyX::Window::GetImage ()"

.PP
Definition at line 1584 of file HiWindow\&.cpp\&.
.SS "\fBEasyWindow\fP HiEasyX::Window::GetInfo ()"

.PP
Definition at line 1574 of file HiWindow\&.cpp\&.
.SS "POINT HiEasyX::Window::GetPos ()"

.PP
Definition at line 1704 of file HiWindow\&.cpp\&.
.SS "long HiEasyX::Window::GetStyle ()"

.PP
Definition at line 1684 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::GetWindowHeight ()"

.PP
Definition at line 1724 of file HiWindow\&.cpp\&.
.SS "SIZE HiEasyX::Window::GetWindowSize ()"

.PP
Definition at line 1709 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::GetWindowWidth ()"

.PP
Definition at line 1719 of file HiWindow\&.cpp\&.
.SS "HWND HiEasyX::Window::InitWindow (int w = \fC640\fP, int h = \fC480\fP, int flag = \fC\fBEW_NORMAL\fP\fP, LPCTSTR lpszWndTitle = \fCL''\fP, WNDPROC WindowProcess = \fCnullptr\fP, HWND hParent = \fCnullptr\fP)"

.PP
Definition at line 1536 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::isAlive ()"

.PP
Definition at line 1579 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::isForegroundWindow ()"

.PP
Definition at line 1739 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::isInTask ()"

.PP
Definition at line 1626 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::isSizeChanged ()"

.PP
Definition at line 1631 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Move (int x, int y)"

.PP
Definition at line 1714 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::MoveRel (int dx, int dy)"

.PP
Definition at line 1729 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::Peek_Message (ExMessage * msg, BYTE filter = \fC\-1\fP, bool removemsg = \fCtrue\fP)"

.PP
Definition at line 1764 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::PreSetPos (int x, int y)"

.PP
Definition at line 1662 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::PreSetStyle (long lStyle)"

.PP
Definition at line 1656 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Redraw ()"

.PP
Definition at line 1679 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::Resize (int w, int h)"

.PP
Definition at line 1734 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::SetExStyle (long lNewExStyle)"

.PP
Definition at line 1699 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::SetProcFunc (WNDPROC WindowProcess)"

.PP
Definition at line 1564 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::SetQuickDraw (UINT nSkipPixels)"

.PP
Definition at line 1668 of file HiWindow\&.cpp\&.
.SS "int HiEasyX::Window::SetStyle (long lNewStyle)"

.PP
Definition at line 1689 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::SetTrayMenu (HMENU hMenu)"

.PP
Definition at line 1646 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::SetTrayMenuProcFunc (void(*)(UINT) pFunc)"

.PP
Definition at line 1651 of file HiWindow\&.cpp\&.
.SS "bool HiEasyX::Window::SetWorkingWindow ()"

.PP
Definition at line 1604 of file HiWindow\&.cpp\&.
.SS "void HiEasyX::Window::WaitMyTask ()"

.PP
Definition at line 1599 of file HiWindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
