.TH "HiEasyX::Static::Char" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::Static::Char
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Static\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TCHAR \fBch\fP"
.br
.ti -1c
.RI "COLORREF \fBcText\fP"
.br
.ti -1c
.RI "COLORREF \fBcBk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Static\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "COLORREF HiEasyX::Static::Char::cBk"

.PP
Definition at line 22 of file Static\&.h\&.
.SS "TCHAR HiEasyX::Static::Char::ch"

.PP
Definition at line 20 of file Static\&.h\&.
.SS "COLORREF HiEasyX::Static::Char::cText"

.PP
Definition at line 21 of file Static\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
