.TH "HiEasyX::SysButton" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysButton
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysButton\&.h>\fP
.PP
Inherits \fBHiEasyX::SysControlBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysButton\fP ()"
.br
.ti -1c
.RI "\fBSysButton\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysButton\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.ti -1c
.RI "LRESULT \fBUpdateMessage\fP (UINT msg, WPARAM wParam, LPARAM lParam, bool &bRet) override"
.br
.ti -1c
.RI "void \fBRegisterMessage\fP (void(*pFunc)())"
.br
.ti -1c
.RI "void \fBImage\fP (bool enable, IMAGE *img=nullptr, bool reserve_text=false)"
.br
.ti -1c
.RI "int \fBGetClickCount\fP ()"
.br
.ti -1c
.RI "bool \fBisClicked\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file SysButton\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::SysButton::SysButton ()"

.PP
Definition at line 18 of file SysButton\&.cpp\&.
.SS "HiEasyX::SysButton::SysButton (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 22 of file SysButton\&.cpp\&.
.SS "HiEasyX::SysButton::SysButton (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 27 of file SysButton\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int HiEasyX::SysButton::GetClickCount ()"

.PP
Definition at line 72 of file SysButton\&.cpp\&.
.SS "void HiEasyX::SysButton::Image (bool enable, IMAGE * img = \fCnullptr\fP, bool reserve_text = \fCfalse\fP)"

.PP
Definition at line 53 of file SysButton\&.cpp\&.
.SS "bool HiEasyX::SysButton::isClicked ()"

.PP
Definition at line 79 of file SysButton\&.cpp\&.
.SS "void HiEasyX::SysButton::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 7 of file SysButton\&.cpp\&.
.SS "void HiEasyX::SysButton::RegisterMessage (void(*)() pFunc)"

.PP
Definition at line 48 of file SysButton\&.cpp\&.
.SS "LRESULT HiEasyX::SysButton::UpdateMessage (UINT msg, WPARAM wParam, LPARAM lParam, bool & bRet)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 32 of file SysButton\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
