.TH "HiEasyX::SysStatic" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysStatic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysStatic\&.h>\fP
.PP
Inherits \fBHiEasyX::SysControlBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysStatic\fP ()"
.br
.ti -1c
.RI "\fBSysStatic\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysStatic\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.ti -1c
.RI "void \fBCenter\fP (bool center)"
.br
.ti -1c
.RI "void \fBImage\fP (bool enable, IMAGE *img=nullptr)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file SysStatic\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::SysStatic::SysStatic ()"

.PP
Definition at line 19 of file SysStatic\&.cpp\&.
.SS "HiEasyX::SysStatic::SysStatic (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 23 of file SysStatic\&.cpp\&.
.SS "HiEasyX::SysStatic::SysStatic (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 28 of file SysStatic\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::SysStatic::Center (bool center)"

.PP
Definition at line 33 of file SysStatic\&.cpp\&.
.SS "void HiEasyX::SysStatic::Image (bool enable, IMAGE * img = \fCnullptr\fP)"

.PP
Definition at line 43 of file SysStatic\&.cpp\&.
.SS "void HiEasyX::SysStatic::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 7 of file SysStatic\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
