.TH "HiEasyX::ScrollBar::ScrollBarInfo" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::ScrollBar::ScrollBarInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScrollBar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbtnW\fP"
.br
.ti -1c
.RI "int \fBbtnH\fP"
.br
.ti -1c
.RI "int \fBslider_free_len\fP"
.br
.ti -1c
.RI "int \fBslider_move_len\fP"
.br
.ti -1c
.RI "int \fBslider_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file ScrollBar\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::btnH"

.PP
Definition at line 25 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::btnW"

.PP
Definition at line 25 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_free_len"

.PP
Definition at line 26 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_len"

.PP
Definition at line 28 of file ScrollBar\&.h\&.
.SS "int HiEasyX::ScrollBar::ScrollBarInfo::slider_move_len"

.PP
Definition at line 27 of file ScrollBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
