.TH "HiEasyX::ControlBase" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::ControlBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ControlBase\&.h>\fP
.PP
Inherits \fBHiEasyX::Container\fP\&.
.PP
Inherited by \fBHiEasyX::Button\fP, \fBHiEasyX::Page\fP, \fBHiEasyX::ProgressCtrl\fP, \fBHiEasyX::ScrollBar\fP, and \fBHiEasyX::Static\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlBase\fP ()"
.br
.ti -1c
.RI "\fBControlBase\fP (std::wstring wstrText)"
.br
.ti -1c
.RI "\fBControlBase\fP (int x, int y, int w=0, int h=0, std::wstring wstrText=L'')"
.br
.ti -1c
.RI "virtual \fB~ControlBase\fP ()"
.br
.ti -1c
.RI "\fBControlBase\fP * \fBGetParent\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetParent\fP (\fBControlBase\fP *p)"
.br
.ti -1c
.RI "virtual bool \fBisAutoSizeForChild\fP () const"
.br
.ti -1c
.RI "virtual void \fBEnableAutoSizeForChild\fP (bool enable)"
.br
.ti -1c
.RI "std::list< \fBControlBase\fP * > & \fBGetChildList\fP ()"
.br
.ti -1c
.RI "size_t \fBGetChildCount\fP ()"
.br
.ti -1c
.RI "virtual void \fBAddChild\fP (\fBControlBase\fP *p, int offset_x=0, int offset_y=0)"
.br
.ti -1c
.RI "virtual void \fBRemoveChild\fP (\fBControlBase\fP *p)"
.br
.ti -1c
.RI "virtual bool \fBisEnabled\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetEnable\fP (bool enable)"
.br
.ti -1c
.RI "virtual bool \fBisVisible\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetVisible\fP (bool visible)"
.br
.ti -1c
.RI "virtual bool \fBGetAutoRedrawState\fP () const"
.br
.ti -1c
.RI "virtual void \fBEnableAutoRedraw\fP (bool enable)"
.br
.ti -1c
.RI "virtual \fBCanvas\fP & \fBGetCanvas\fP ()"
.br
.ti -1c
.RI "virtual COLORREF \fBGetBkColor\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetBkColor\fP (COLORREF color)"
.br
.ti -1c
.RI "virtual COLORREF \fBGetTextColor\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetTextColor\fP (COLORREF color)"
.br
.ti -1c
.RI "virtual void \fBEnableBorder\fP (bool bEnableBorder, COLORREF color=BLACK, int thickness=1)"
.br
.ti -1c
.RI "virtual void \fBSetAlpha\fP (BYTE alpha, bool bUseCanvasAlpha, bool isAlphaCalculated)"
.br
.ti -1c
.RI "virtual std::wstring \fBGetText\fP () const"
.br
.ti -1c
.RI "virtual void \fBSetText\fP (std::wstring wstr)"
.br
.ti -1c
.RI "virtual void \fBDraw_Text\fP (int nTextOffsetX=0, int nTextOffsetY=0)"
.br
.ti -1c
.RI "virtual void \fBRedraw\fP ()"
.br
.ti -1c
.RI "virtual void \fBDraw\fP (bool draw_child=true)"
.br
.ti -1c
.RI "virtual void \fBRender\fP (\fBCanvas\fP *dst, RECT *pRct=nullptr, int *pCount=0)"
.br
.ti -1c
.RI "virtual void \fBSetMsgProcFunc\fP (\fBMESSAGE_PROC_FUNC\fP func)"
.br
.ti -1c
.RI "virtual void \fBSetMsgProcFunc\fP (\fBMESSAGE_PROC_FUNC_CLASS\fP static_class_func, void *_this)"
.br
.ti -1c
.RI "virtual void \fBUpdateMessage\fP (ExMessage msg)"
.br
.ti -1c
.RI "virtual bool \fBisHovered\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisFocused\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisPressed\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateRect\fP (RECT rctOld) override"
.br
.ti -1c
.RI "void \fBMarkNeedRedrawAndRender\fP ()"
.br
.ti -1c
.RI "void \fBMarkNeedClearRect\fP (RECT rct)"
.br
.ti -1c
.RI "virtual void \fBDrawChild\fP ()"
.br
.ti -1c
.RI "virtual ExMessage & \fBTransformMessage\fP (ExMessage &msg)"
.br
.ti -1c
.RI "virtual void \fBCallUserMsgProcFunc\fP (int msgid, ExMessage msg)"
.br
.ti -1c
.RI "virtual void \fBChildRectChanged\fP (\fBControlBase\fP *pChild)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_bEnabled\fP = true"
.br
.ti -1c
.RI "bool \fBm_bVisible\fP = true"
.br
.ti -1c
.RI "bool \fBm_bAutoRedrawWhenReceiveMsg\fP = true"
.br
.ti -1c
.RI "bool \fBm_bRedraw\fP = true"
.br
.ti -1c
.RI "bool \fBm_bRender\fP = true"
.br
.ti -1c
.RI "bool \fBm_bClear\fP = false"
.br
.ti -1c
.RI "RECT \fBm_rctClear\fP = { 0 }"
.br
.ti -1c
.RI "bool \fBm_bAlwaysRedrawAndRender\fP = false"
.br
.ti -1c
.RI "std::wstring \fBm_wstrText\fP"
.br
.ti -1c
.RI "\fBCanvas\fP \fBm_canvas\fP"
.br
.ti -1c
.RI "BYTE \fBm_alpha\fP = 255"
.br
.ti -1c
.RI "bool \fBm_bUseCanvasAlpha\fP = false"
.br
.ti -1c
.RI "bool \fBm_isAlphaCalculated\fP = false"
.br
.ti -1c
.RI "COLORREF \fBm_cBorder\fP = \fBMODERN_BORDER_GRAY\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cBackground\fP = \fBCLASSICGRAY\fP"
.br
.ti -1c
.RI "COLORREF \fBm_cText\fP = BLACK"
.br
.ti -1c
.RI "bool \fBm_bEnableBorder\fP = true"
.br
.ti -1c
.RI "int \fBm_nBorderThickness\fP = 1"
.br
.ti -1c
.RI "bool \fBm_bCompleteFirstSetRect\fP = false"
.br
.ti -1c
.RI "\fBControlBase\fP * \fBm_pParent\fP = nullptr"
.br
.ti -1c
.RI "std::list< \fBControlBase\fP * > \fBm_listChild\fP"
.br
.ti -1c
.RI "bool \fBm_bAutoSizeForChild\fP = false"
.br
.ti -1c
.RI "\fBMESSAGE_PROC_FUNC\fP \fBm_funcMessageProc\fP = nullptr"
.br
.ti -1c
.RI "\fBMESSAGE_PROC_FUNC_CLASS\fP \fBm_funcMessageProc_Class\fP = nullptr"
.br
.ti -1c
.RI "void * \fBm_pCalledClass\fP = nullptr"
.br
.ti -1c
.RI "bool \fBm_bHovered\fP = false"
.br
.ti -1c
.RI "bool \fBm_bPressed\fP = false"
.br
.ti -1c
.RI "bool \fBm_bFocused\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file ControlBase\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::ControlBase::ControlBase ()"

.PP
Definition at line 14 of file ControlBase\&.cpp\&.
.SS "HiEasyX::ControlBase::ControlBase (std::wstring wstrText)"

.PP
Definition at line 19 of file ControlBase\&.cpp\&.
.SS "HiEasyX::ControlBase::ControlBase (int x, int y, int w = \fC0\fP, int h = \fC0\fP, std::wstring wstrText = \fCL''\fP)"

.PP
Definition at line 25 of file ControlBase\&.cpp\&.
.SS "HiEasyX::ControlBase::~ControlBase ()\fC [virtual]\fP"

.PP
Definition at line 32 of file ControlBase\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::ControlBase::AddChild (\fBControlBase\fP * p, int offset_x = \fC0\fP, int offset_y = \fC0\fP)\fC [virtual]\fP"

.PP
Definition at line 118 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::CallUserMsgProcFunc (int msgid, ExMessage msg)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 368 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::ChildRectChanged (\fBControlBase\fP * pChild)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 380 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::Draw (bool draw_child = \fCtrue\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::ScrollBar\fP, \fBHiEasyX::ProgressCtrl\fP, \fBHiEasyX::Static\fP, and \fBHiEasyX::Button\fP\&.
.PP
Definition at line 224 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::Draw_Text (int nTextOffsetX = \fC0\fP, int nTextOffsetY = \fC0\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::Static\fP\&.
.PP
Definition at line 205 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::DrawChild ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 246 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::EnableAutoRedraw (bool enable)\fC [virtual]\fP"

.PP
Definition at line 154 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::EnableAutoSizeForChild (bool enable)\fC [virtual]\fP"

.PP
Definition at line 100 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::EnableBorder (bool bEnableBorder, COLORREF color = \fCBLACK\fP, int thickness = \fC1\fP)\fC [virtual]\fP"

.PP
Definition at line 175 of file ControlBase\&.cpp\&.
.SS "virtual bool HiEasyX::ControlBase::GetAutoRedrawState () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 150 of file ControlBase\&.h\&.
.SS "virtual COLORREF HiEasyX::ControlBase::GetBkColor () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 157 of file ControlBase\&.h\&.
.SS "virtual \fBCanvas\fP& HiEasyX::ControlBase::GetCanvas ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 155 of file ControlBase\&.h\&.
.SS "size_t HiEasyX::ControlBase::GetChildCount ()"

.PP
Definition at line 110 of file ControlBase\&.cpp\&.
.SS "std::list< \fBControlBase\fP * > & HiEasyX::ControlBase::GetChildList ()"

.PP
Definition at line 105 of file ControlBase\&.cpp\&.
.SS "\fBControlBase\fP* HiEasyX::ControlBase::GetParent ()\fC [inline]\fP"

.PP
Definition at line 123 of file ControlBase\&.h\&.
.SS "virtual std::wstring HiEasyX::ControlBase::GetText () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 169 of file ControlBase\&.h\&.
.SS "virtual COLORREF HiEasyX::ControlBase::GetTextColor () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 161 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isAutoSizeForChild () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 128 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isEnabled () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 142 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isFocused () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 197 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isHovered () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 194 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isPressed () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 200 of file ControlBase\&.h\&.
.SS "virtual bool HiEasyX::ControlBase::isVisible () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 146 of file ControlBase\&.h\&.
.SS "void HiEasyX::ControlBase::MarkNeedClearRect (RECT rct)\fC [protected]\fP"

.PP
Definition at line 72 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::MarkNeedRedrawAndRender ()\fC [protected]\fP"

.PP
Definition at line 62 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::Redraw ()\fC [virtual]\fP"

.PP
Definition at line 218 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::RemoveChild (\fBControlBase\fP * p)\fC [virtual]\fP"

.PP
Definition at line 131 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::Render (\fBCanvas\fP * dst, RECT * pRct = \fCnullptr\fP, int * pCount = \fC0\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::Page\fP\&.
.PP
Definition at line 254 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetAlpha (BYTE alpha, bool bUseCanvasAlpha, bool isAlphaCalculated)\fC [virtual]\fP"

.PP
Definition at line 189 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetBkColor (COLORREF color)\fC [virtual]\fP"

.PP
Definition at line 159 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetEnable (bool enable)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::Button\fP\&.
.PP
Definition at line 78 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetMsgProcFunc (\fBMESSAGE_PROC_FUNC\fP func)\fC [virtual]\fP"

.PP
Definition at line 340 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetMsgProcFunc (\fBMESSAGE_PROC_FUNC_CLASS\fP static_class_func, void * _this)\fC [virtual]\fP"

.PP
Definition at line 347 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetParent (\fBControlBase\fP * p)\fC [virtual]\fP"

.PP
Definition at line 85 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetText (std::wstring wstr)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::Static\fP\&.
.PP
Definition at line 198 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetTextColor (COLORREF color)\fC [virtual]\fP"

.PP
Definition at line 167 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::SetVisible (bool visible)\fC [virtual]\fP"

.PP
Definition at line 138 of file ControlBase\&.cpp\&.
.SS "ExMessage & HiEasyX::ControlBase::TransformMessage (ExMessage & msg)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 354 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::UpdateMessage (ExMessage msg)\fC [virtual]\fP"

.PP
Reimplemented in \fBHiEasyX::ScrollBar\fP, and \fBHiEasyX::Button\fP\&.
.PP
Definition at line 391 of file ControlBase\&.cpp\&.
.SS "void HiEasyX::ControlBase::UpdateRect (RECT rctOld)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::Container\fP\&.
.PP
Reimplemented in \fBHiEasyX::ScrollBar\fP\&.
.PP
Definition at line 36 of file ControlBase\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "BYTE HiEasyX::ControlBase::m_alpha = 255\fC [protected]\fP"

.PP
Definition at line 62 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bAlwaysRedrawAndRender = false\fC [protected]\fP"

.PP
Definition at line 57 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bAutoRedrawWhenReceiveMsg = true\fC [protected]\fP"

.PP
Definition at line 52 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bAutoSizeForChild = false\fC [protected]\fP"

.PP
Definition at line 78 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bClear = false\fC [protected]\fP"

.PP
Definition at line 55 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bCompleteFirstSetRect = false\fC [protected]\fP"

.PP
Definition at line 73 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bEnableBorder = true\fC [protected]\fP"

.PP
Definition at line 70 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bEnabled = true\fC [protected]\fP"

.PP
Definition at line 48 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bFocused = false\fC [protected]\fP"

.PP
Definition at line 86 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bHovered = false\fC [protected]\fP"

.PP
Definition at line 84 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bPressed = false\fC [protected]\fP"

.PP
Definition at line 85 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bRedraw = true\fC [protected]\fP"

.PP
Definition at line 53 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bRender = true\fC [protected]\fP"

.PP
Definition at line 54 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bUseCanvasAlpha = false\fC [protected]\fP"

.PP
Definition at line 63 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_bVisible = true\fC [protected]\fP"

.PP
Definition at line 49 of file ControlBase\&.h\&.
.SS "\fBCanvas\fP HiEasyX::ControlBase::m_canvas\fC [protected]\fP"

.PP
Definition at line 61 of file ControlBase\&.h\&.
.SS "COLORREF HiEasyX::ControlBase::m_cBackground = \fBCLASSICGRAY\fP\fC [protected]\fP"

.PP
Definition at line 67 of file ControlBase\&.h\&.
.SS "COLORREF HiEasyX::ControlBase::m_cBorder = \fBMODERN_BORDER_GRAY\fP\fC [protected]\fP"

.PP
Definition at line 66 of file ControlBase\&.h\&.
.SS "COLORREF HiEasyX::ControlBase::m_cText = BLACK\fC [protected]\fP"

.PP
Definition at line 68 of file ControlBase\&.h\&.
.SS "\fBMESSAGE_PROC_FUNC\fP HiEasyX::ControlBase::m_funcMessageProc = nullptr\fC [protected]\fP"

.PP
Definition at line 80 of file ControlBase\&.h\&.
.SS "\fBMESSAGE_PROC_FUNC_CLASS\fP HiEasyX::ControlBase::m_funcMessageProc_Class = nullptr\fC [protected]\fP"

.PP
Definition at line 81 of file ControlBase\&.h\&.
.SS "bool HiEasyX::ControlBase::m_isAlphaCalculated = false\fC [protected]\fP"

.PP
Definition at line 64 of file ControlBase\&.h\&.
.SS "std::list<\fBControlBase\fP*> HiEasyX::ControlBase::m_listChild\fC [protected]\fP"

.PP
Definition at line 76 of file ControlBase\&.h\&.
.SS "int HiEasyX::ControlBase::m_nBorderThickness = 1\fC [protected]\fP"

.PP
Definition at line 71 of file ControlBase\&.h\&.
.SS "void* HiEasyX::ControlBase::m_pCalledClass = nullptr\fC [protected]\fP"

.PP
Definition at line 82 of file ControlBase\&.h\&.
.SS "\fBControlBase\fP* HiEasyX::ControlBase::m_pParent = nullptr\fC [protected]\fP"

.PP
Definition at line 75 of file ControlBase\&.h\&.
.SS "RECT HiEasyX::ControlBase::m_rctClear = { 0 }\fC [protected]\fP"

.PP
Definition at line 56 of file ControlBase\&.h\&.
.SS "std::wstring HiEasyX::ControlBase::m_wstrText\fC [protected]\fP"

.PP
Definition at line 59 of file ControlBase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
