.TH "HiEasyX::SysComboBox" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HiEasyX::SysComboBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SysComboBox\&.h>\fP
.PP
Inherits \fBHiEasyX::SysControlBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSysComboBox\fP ()"
.br
.ti -1c
.RI "\fBSysComboBox\fP (HWND hParent, RECT rct, std::wstring strText=L'')"
.br
.ti -1c
.RI "\fBSysComboBox\fP (HWND hParent, int x, int y, int w, int h, std::wstring strText=L'')"
.br
.ti -1c
.RI "void \fBPreSetEtyle\fP (bool always_show_list, bool editable, bool sort)"
.br
.ti -1c
.RI "LRESULT \fBUpdateMessage\fP (UINT msg, WPARAM wParam, LPARAM lParam, bool &bRet) override"
.br
.ti -1c
.RI "void \fBRegisterSelMessage\fP (void(*pFunc)(int sel, std::wstring wstrSelText))"
.br
.ti -1c
.RI "void \fBRegisterEditMessage\fP (void(*pFunc)(std::wstring wstrText))"
.br
.ti -1c
.RI "int \fBGetSel\fP () const"
.br
.ti -1c
.RI "void \fBSetSel\fP (int sel)"
.br
.ti -1c
.RI "bool \fBSelectString\fP (std::wstring wstrText)"
.br
.ti -1c
.RI "void \fBAddString\fP (std::wstring wstrText)"
.br
.ti -1c
.RI "void \fBInsertString\fP (int index, std::wstring wstrText)"
.br
.ti -1c
.RI "void \fBDeleteString\fP (int index)"
.br
.ti -1c
.RI "int \fBGetCount\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBShowDropdown\fP (bool enable)"
.br
.ti -1c
.RI "bool \fBisSelChanged\fP ()"
.br
.ti -1c
.RI "bool \fBisEdited\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRealCreate\fP (HWND hParent) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file SysComboBox\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HiEasyX::SysComboBox::SysComboBox ()"

.PP
Definition at line 25 of file SysComboBox\&.cpp\&.
.SS "HiEasyX::SysComboBox::SysComboBox (HWND hParent, RECT rct, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 29 of file SysComboBox\&.cpp\&.
.SS "HiEasyX::SysComboBox::SysComboBox (HWND hParent, int x, int y, int w, int h, std::wstring strText = \fCL''\fP)"

.PP
Definition at line 34 of file SysComboBox\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HiEasyX::SysComboBox::AddString (std::wstring wstrText)"

.PP
Definition at line 122 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::Clear ()"

.PP
Definition at line 142 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::DeleteString (int index)"

.PP
Definition at line 132 of file SysComboBox\&.cpp\&.
.SS "int HiEasyX::SysComboBox::GetCount ()"

.PP
Definition at line 137 of file SysComboBox\&.cpp\&.
.SS "int HiEasyX::SysComboBox::GetSel () const\fC [inline]\fP"

.PP
Definition at line 56 of file SysComboBox\&.h\&.
.SS "void HiEasyX::SysComboBox::InsertString (int index, std::wstring wstrText)"

.PP
Definition at line 127 of file SysComboBox\&.cpp\&.
.SS "bool HiEasyX::SysComboBox::isEdited ()"

.PP
Definition at line 159 of file SysComboBox\&.cpp\&.
.SS "bool HiEasyX::SysComboBox::isSelChanged ()"

.PP
Definition at line 152 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::PreSetEtyle (bool always_show_list, bool editable, bool sort)"

.PP
Definition at line 39 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::RealCreate (HWND hParent)\fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 5 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::RegisterEditMessage (void(*)(std::wstring wstrText) pFunc)"

.PP
Definition at line 106 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::RegisterSelMessage (void(*)(int sel, std::wstring wstrSelText) pFunc)"

.PP
Definition at line 101 of file SysComboBox\&.cpp\&.
.SS "bool HiEasyX::SysComboBox::SelectString (std::wstring wstrText)"

.PP
Definition at line 117 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::SetSel (int sel)"

.PP
Definition at line 111 of file SysComboBox\&.cpp\&.
.SS "void HiEasyX::SysComboBox::ShowDropdown (bool enable)"

.PP
Definition at line 147 of file SysComboBox\&.cpp\&.
.SS "LRESULT HiEasyX::SysComboBox::UpdateMessage (UINT msg, WPARAM wParam, LPARAM lParam, bool & bRet)\fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBHiEasyX::SysControlBase\fP\&.
.PP
Definition at line 66 of file SysComboBox\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
