.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiFPS.cpp" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiFPS.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HiFPS\&.h'\fP
.br
\fC#include 'HiFunc\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHiEasyX::DelayFPS\fP (int fps, bool wait_long)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "clock_t \fBHiEasyX::tRecord\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
