.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiFunc.cpp" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiFunc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HiFunc\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBScreenSize\fP \fBGetScreenSize\fP ()"
.br
.ti -1c
.RI "void \fBGetImageSize\fP (IMAGE *pImg, int &width, int &height)"
.br
.ti -1c
.RI "DWORD * \fBReverseAlpha\fP (DWORD *\fBpBuf\fP, int size)"
.br
.ti -1c
.RI "HBITMAP \fBImage2Bitmap\fP (IMAGE *img, bool enable_alpha)"
.br
.ti -1c
.RI "HICON \fBBitmap2Icon\fP (HBITMAP hBmp)"
.br
.ti -1c
.RI "void \fBHpSleep\fP (int ms)"
.br
.ti -1c
.RI "bool \fBisInRect\fP (int x, int y, RECT rct)"
.br
.ti -1c
.RI "UINT \fBGetExMessageType\fP (ExMessage msg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "HICON Bitmap2Icon (HBITMAP hBmp)"

.PP
Definition at line 60 of file HiFunc\&.cpp\&.
.SS "UINT GetExMessageType (ExMessage msg)"

.PP
Definition at line 100 of file HiFunc\&.cpp\&.
.SS "void GetImageSize (IMAGE * pImg, int & width, int & height)"

.PP
Definition at line 17 of file HiFunc\&.cpp\&.
.SS "\fBScreenSize\fP GetScreenSize ()"

.PP
Definition at line 6 of file HiFunc\&.cpp\&.
.SS "void HpSleep (int ms)"

.PP
Definition at line 78 of file HiFunc\&.cpp\&.
.SS "HBITMAP Image2Bitmap (IMAGE * img, bool enable_alpha)"

.PP
Definition at line 47 of file HiFunc\&.cpp\&.
.SS "bool isInRect (int x, int y, RECT rct)"

.PP
Definition at line 93 of file HiFunc\&.cpp\&.
.SS "DWORD* ReverseAlpha (DWORD * pBuf, int size)"

.PP
Definition at line 37 of file HiFunc\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
