.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/HiGUI.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiGUI/HiGUI.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Page\&.h'\fP
.br
\fC#include 'Static\&.h'\fP
.br
\fC#include 'Button\&.h'\fP
.br
\fC#include 'ProgressCtrl\&.h'\fP
.br
\fC#include 'ScrollBar\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
