.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.cpp" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HiIcon\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "DWORD \fBpBuf\fP [\fBHIICON_WIDTH\fP *\fBHIICON_HEIGHT\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "DWORD pBuf[\fBHIICON_WIDTH\fP *\fBHIICON_HEIGHT\fP]"

.PP
Definition at line 3 of file HiIcon\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
