.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiIcon.h
.SH SYNOPSIS
.br
.PP
\fC#include <graphics\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHIICON_WIDTH\fP   64"
.br
.ti -1c
.RI "#define \fBHIICON_HEIGHT\fP   64"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "DWORD * \fBHiEasyX::GetIconImageBuffer\fP ()"
.br
.ti -1c
.RI "IMAGE * \fBHiEasyX::GetIconImage\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HIICON_HEIGHT   64"

.PP
Definition at line 15 of file HiIcon\&.h\&.
.SS "#define HIICON_WIDTH   64"

.PP
Definition at line 14 of file HiIcon\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
