.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiMouseDrag.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiMouseDrag.h
.SH SYNOPSIS
.br
.PP
\fC#include <graphics\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::MouseDrag\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
