.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiStart.cpp" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiStart.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HiStart\&.h'\fP
.br
\fC#include <graphics\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisEdgePoint\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBGetDstPoints\fP ()"
.br
.ti -1c
.RI "void \fBGetSrcPoints\fP ()"
.br
.ti -1c
.RI "void \fBBlur\fP (DWORD *pMem)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "POINT * \fBg_pDst\fP"
.br
.ti -1c
.RI "POINT * \fBg_pSrc\fP"
.br
.ti -1c
.RI "int \fBg_nWidth\fP"
.br
.ti -1c
.RI "int \fBg_nHeight\fP"
.br
.ti -1c
.RI "int \fBg_nCount\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Blur (DWORD * pMem)"

.PP
Definition at line 95 of file HiStart\&.cpp\&.
.SS "void GetDstPoints ()"

.PP
Definition at line 36 of file HiStart\&.cpp\&.
.SS "void GetSrcPoints ()"

.PP
Definition at line 80 of file HiStart\&.cpp\&.
.SS "bool isEdgePoint (int x, int y)"

.PP
Definition at line 14 of file HiStart\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int g_nCount"

.PP
Definition at line 11 of file HiStart\&.cpp\&.
.SS "int g_nHeight"

.PP
Definition at line 10 of file HiStart\&.cpp\&.
.SS "int g_nWidth"

.PP
Definition at line 9 of file HiStart\&.cpp\&.
.SS "POINT* g_pDst"

.PP
Definition at line 7 of file HiStart\&.cpp\&.
.SS "POINT* g_pSrc"

.PP
Definition at line 8 of file HiStart\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
