.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/HiSysGUI.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/HiSysGUI.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./HiDef\&.h'\fP
.br
\fC#include 'SysGroup\&.h'\fP
.br
\fC#include 'SysGroupBox\&.h'\fP
.br
\fC#include 'SysStatic\&.h'\fP
.br
\fC#include 'SysButton\&.h'\fP
.br
\fC#include 'SysCheckBox\&.h'\fP
.br
\fC#include 'SysRadioButton\&.h'\fP
.br
\fC#include 'SysEdit\&.h'\fP
.br
\fC#include 'SysComboBox\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
