.TH "ScreenSize" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScreenSize
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HiFunc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBleft\fP"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file HiFunc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ScreenSize::h"

.PP
Definition at line 19 of file HiFunc\&.h\&.
.SS "int ScreenSize::left"

.PP
Definition at line 16 of file HiFunc\&.h\&.
.SS "int ScreenSize::top"

.PP
Definition at line 17 of file HiFunc\&.h\&.
.SS "int ScreenSize::w"

.PP
Definition at line 18 of file HiFunc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
