.TH "E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.h" 3 "Sat Aug 13 2022" "Version Ver0.2(alpha)" "HiEasyX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/_MYC/_VS_Project/HiEasyX/HiEasyX/HiEasyX/HiSysGUI/SysControlBase.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./HiContainer\&.h'\fP
.br
\fC#include <windowsx\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHiEasyX::SysControlBase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHiEasyX\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHiEasyX::SysControlType\fP { \fBHiEasyX::SCT_Unknown\fP, \fBHiEasyX::SCT_Group\fP, \fBHiEasyX::SCT_GroupBox\fP, \fBHiEasyX::SCT_Static\fP, \fBHiEasyX::SCT_Button\fP, \fBHiEasyX::SCT_CheckBox\fP, \fBHiEasyX::SCT_RadioButton\fP, \fBHiEasyX::SCT_Edit\fP, \fBHiEasyX::SCT_ComboBox\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBHiEasyX::AllocID\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HiEasyX from the source code\&.
